### ISSUE TITLE
Опечатка?

### ISSUE THREAD

**Issue by YaroslavBemov** [SonyaHon/GeekBrainsNodeJsEp2#1]
https://github.com/SonyaHon/GeekBrainsNodeJsEp2/blob/7da2e1e0139f835c731fe1e33cea4a77ee97e0b9/src/index.js#L33

Наверное, здесть должен быть - emit.

**Comment by SonyaHon** [comment]
Нет, здесь было показано, что можно поставить несколько слушателей на 1 евент
